default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: barber_shops_api_development
  username: postgres
  password: sekret
  host: localhost
  port: 5432

test:
  <<: *default
  database: barber_shops_api_test

production:
  <<: *default
  database: <%= ENV["BARBER_SHOPS_API_DATABASE_NAME"] %>
  username: <%= ENV["BARBER_SHOPS_API_DATABASE_USERNAME"] %>
  password: <%= ENV["BARBER_SHOPS_API_DATABASE_PASSWORD"] %>
  host: <%= ENV["BARBER_SHOPS_API_DATABASE_HOST"] %>
  port: 5432

